### ISSUE TITLE
Line in Problem

### ISSUE THREAD

**Issue by jeurgenK** [donnersm/FFT_ESP32_Analyzer#5]
Hello,
I have a problem connecting to the output of my mixer. I can't get a reasonable level to drive the ESP32's input. Attempts to switch on a preamp brought no result. The proposed line circuit needs too high a level. What should I do ?
With the MIC MAX4466 there is no problem. But I don't want to use a MIC.

That was unsuccessful.
https://de.aliexpress.com/item/32960059477.html?spm=a2g0o.productlist.0.0.334a15bffeOFjb&algo_pvid=cbf4c21e-9e10-4301-ab81-e87346bcd13a&algo_exp_id=cbf4c21e-9e10-4301-ab81-e87346bcd13a-21&pdp_ext_f=%7B%22sku_id%22%3A%2210000015686407668%22%7D&pdp_npi=2%40dis%21EUR%2112.54%2110.16%21%21%21%21%21%400b0a050b16626698306171794ee7f8%2110000015686407668%21sea&curPageLogUid=ApJQoSVgHZSY

That was unsuccessful. I had tried several preamps.

Kind regards
J.Kommos

**Comment by donnersm** [comment]
What is your audio source? When the problem occurs, is your usb plugged in to microcontroller? 
did u adjust the potmeter for the line input to the correct level?  Send me some photos if the setup, the pcb top and bottom side. Whatsapp +31651875108

**Comment by jeurgenK** [comment]
Hi Mark,
Thank you very much for your quick reply. I'll put together some photos and send them over. It's just a test setup for me. I haven't ordered the original yet because it comes from England and takes a long time. But I will still order.

Best regards from Cologne
Juergen

**Comment by donnersm** [comment]
England? I live in holland and i ship from holland lol

Verstuurd vanaf mijn iPhone

**Comment by jeurgenK** [comment]
When ordering, I am offered England ? Or did I look wrong?

**Comment by jeurgenK** [comment]
Sorry, that was my fault. I had a different circuit board in mind.

**Comment by jeurgenK** [comment]
Hi Mark,
The project is great. I also tested this with 64*16 LED. Just beautiful. The circuit corresponds to the circuit diagram. I will then order this board and then I will check it on the original board. I don't know how long the order will take? I ordered another circuit board. Just take a look.

New trial.I hope this solves my problem.
https://de.elv.com/elv-aufhol-verstaerker-ahv-100-komplettbausatz-ohne-gehaeuse-056393

I will then report what the result is.

Kind regards
Juergen

**Comment by jeurgenK** [comment]
Hello Mark,
I will try the tests you suggested.
Juergen

**Comment by jeurgenK** [comment]
Hi Mark,
this shows up when doing a test with the calibration. Is that right ?

BandCalibration_XXXX[64]=
{ 17.50, 1.19, 1.00, 1.18, 3.85, 4.17, 4.32, 6.25, 6.60, 3.30, 3.57, 3.65, 6.14, 5.38, 9.72, 13.46, 21.88, 4.86, 3.40, 10.00, 38.89, 20.59, 19.44, 31.82, 6.48, 4.73, 2.82, 3.68, 14.00, 50.00, 29.17, 5.56, 5.15, 7.29, 10.61, 29.17, 38.89, 116.67, 175.00, 26.92, 17.50, 10.61, 58.33, 4.93, 10.94, 6.25, inf, 350.00, inf, 175.00, 38.89, 70.00, 175.00, inf, 10.61, 5.07, 87.50, 9.46, inf, 350.00, inf, inf, inf, inf };

**Comment by donnersm** [comment]
It shows inf on some channels , so the input noice on that channel is not good. Are you using a noice source to do this


Verstuurd vanaf mijn iPad

**Comment by jeurgenK** [comment]
Hello Mark,
Yes, the noise was generated with the Adacity program and fed to the FFT with the Symsung S10.
I have no other idea or what should I do.

**Comment by donnersm** [comment]
Thats not a good noise source… the bandwith of phone and tabled is limited. Btw no need to recalibrate…i ment just activate it in normal mode . See the manual on how to do that… its something like double press on of the buttons

**Comment by jeurgenK** [comment]
HiMark,

first of all thank you for your support. I will now do the tests again with HIFI Equitment. You have to know all that first. Once again, thank you very much for your help.

Kind regards
Juergen

**Comment by flasher69** [comment]
Hi Juergen,

I also had to connect directly to an amp. From low sound sources such as a phone I had no luck getting it to work.
You need also to adjust the R23/R9 a lot until you get it right.

**Comment by jeurgenK** [comment]
Hi flasher69,
thank you very much for your help.
